Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
import numpy as np
import pandas as pd

In [4]:
a=np.arange(12,24)

In [5]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [39]:
b=[a.reshape (i, int(12/i)) for i in range (2,13) if 12%i ==0]
for item in b:
    print (item)
    print ()


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]



Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [40]:
a.reshape (2,-1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [41]:
a.reshape (3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
a.reshape (6,-1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [46]:
a.reshape (-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [48]:
a.reshape (-1,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


НЕТ (?)

In [64]:
c=np.arange (1,13).reshape(-1,1)
print (c)
print("Размерность C: {}".format(c.ndim))
            

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Размерность C: 2


Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [7]:
d = np.random.randn(3, 4)
print(d)

[[-0.19030377  1.88267841 -1.70309768  0.0018992 ]
 [ 1.26209522 -0.39096367  1.29744386 -0.5254613 ]
 [-0.11463747 -0.78691421  0.55190273  0.95761244]]


In [8]:
np.size (d)

12

In [10]:
e = d.flatten()
print (e)

[-0.19030377  1.88267841 -1.70309768  0.0018992   1.26209522 -0.39096367
  1.29744386 -0.5254613  -0.11463747 -0.78691421  0.55190273  0.95761244]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [13]:
a = np.arange(20, 0, -2)
print (a)

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [14]:
b = np.arange(20, 1, -2).reshape (-1,1)
print (b)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


Разная размерность массивов

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [17]:
a = np.zeros((2, 2))

b = np.ones((3, 2))

In [18]:
c = np.vstack((a, b))

print(c)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [24]:
a=np.arange (0,12)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
A = a.reshape (4,3)
print (A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
At = A.T

In [28]:
print (At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [29]:
B = np.dot(A, At)

In [30]:
print (B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [32]:
d = np.linalg.det(B)
print("Размерность B: {}".format(B.ndim))

print("Ранг B: {}". format (d))

Размерность B: 2
Ранг B: 0.0


Нельзя получить обратную матрицу, поскольку ранг исходной матрицы равен 0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [39]:
np.random.seed(42)
c=np.random.randint(0,16,16)
print (c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]
